### ISSUE TITLE
微信自动勾选发送原图后想取消勾选又会自动被勾上

### ISSUE THREAD

**Issue by hyue418** [aoguai/subscription#273]
### 一些验证

- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/aoguai/subscription) 导致
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### BUG描述

微信自动勾选发送原图后，部分图片/视频不想发送原图，点取消勾选然后又会被立刻再勾上，无法取消勾选。希望规则能改为只帮勾选一次。

### 请输入 误触/不执行规则 的界面的快照, 或者生成的快照链接。
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

微信自动勾选发送原图后，部分图片/视频不想发送原图，点取消勾选然后又会被立刻再勾上，无法取消勾选。希望规则能改为只帮勾选一次。

**Comment by aoguai** [comment]
这种情况不是规则能解决的，因为 GKD 虽然可以通过 [actionMaximum​](https://gkd.li/api/interfaces/RawGlobalGroup#actionmaximum) 来设置规则的 action 被执行的最大次数, 达到最大次数时, 休眠此规则。但是这一般仅,适用于只需要执行一次的: 开屏广告/更新弹窗/青少年弹窗 一类规则。

像这种功能性质的规则，设置这个会影响需要全部 图片/视频 发送原图的用户使用体验。

二者不能兼得，您可以一次性选择完图片后手动暂时关闭规则，发送完成后再开启。

**Comment by aoguai** [comment]
https://github.com/aoguai/subscription/releases/tag/v47

**Comment by hyue418** [comment]
感谢大佬！
