### ISSUE TITLE
掌上公交运行中弹出的广告窗口无法跳过

### ISSUE THREAD

**Issue by kunanhai5888** [aoguai/subscription#50]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/aoguai/subscription) 导致

- [X] 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/import/14548109

**Comment by adproqwq** [comment]
本仓库不适配该应用。因为其并不在适配应用清单内

**Comment by kunanhai5888** [comment]
thank you
